[theme]
primaryColor="#c95792"
backgroundColor="#1f1846"
secondaryBackgroundColor="#7c4585"
textColor="#ffffff"

#primaryColor="#76bbce"
#backgroundColor="#b25489"
#secondaryBackgroundColor="#64115a"
#textColor="#ffebeb"
